import {
  ADD_TO_CART,
  GET_NUMBERS_BASKET,
  INCREASE_QUANTITY,
  DECREASE_QUANTITY,
  CLEAR_PRODUCT,
} from "../actions/types";
const initialState = {
  cart: 0,
  cartPrice: 0,
  products: {
    moong: {
      name: "Moong",
      price: 1,
      tagName: "moong",
      numbers: 0,
      inCart: false,
      imageUrl: "/images/of.png",
    },
    sunfloweroil: {
      name: "Sunflower oil",
      price: 9,
      tagName: "sunfloweroil",
      imageUrl: "/images/of1.png",
      numbers: 0,
      inCart: false,
    },
    kabulichana: {
      name: "Kabuli Chana(1 kg)",
      imageUrl: "/images/of2.png",
      price: 3,
      tagName: "kabulichana",
      numbers: 0,
      inCart: false,
    },
    soyachunks: {
      imageUrl: "/images/of3.png",
      name: "Soya Chunks(1 kg)",
      price: 3.5,
      tagName: "soyachunks",
      numbers: 0,
      inCart: false,
    },
    moisturiser: {
      name: "Moisturiser",
      price: 6.0,
      tagName: "moisturiser",
      imageUrl: "/images/of16.png",
      targetModal: "#myModal17",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(500 g)",
    },
    ladyfinger: {
      name: "Lady Finger",
      price: 4.5,
      tagName: "ladyfinger",
      imageUrl: "/images/of17.png",
      targetModal: "#myModal8",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(250 g)",
    },
    ribbon: {
      name: "Ribbon",
      price: 3.5,
      tagName: "ribbon",
      imageUrl: "/images/of18.png",
      targetModal: "#myModal9",
      numbers: 0,
      inCart: false,
      labelPrice: "4.00",
      itemWeight: "(1 pc)",
    },
    grapes: {
      name: "Grapes",
      price: 0.8,
      tagName: "grapes",
      imageUrl: "/images/of20.png",
      targetModal: "#myModa21",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(1 pack)",
    },
    clips: {
      name: "Clips",
      price: 6,
      tagName: "clips",
      imageUrl: "/images/of20.png",
      targetModal: "#myModal21",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(1 pack)",
      isOffer: false,
    },
    conditioner: {
      name: "Conditioner",
      price: 4.5,
      tagName: "conditioner",
      imageUrl: "/images/of21.png",
      targetModal: "#myModal22",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(250 g)",
      isOffer: false,
    },
    cleaner: {
      name: "Cleaner",
      price: 3,
      tagName: "cleaner",
      imageUrl: "/images/of22.png",
      targetModal: "#myModal23",
      numbers: 0,
      inCart: false,
      labelPrice: "4.00",
      itemWeight: "(250 kg)",
      isOffer: false,
    },
    gel: {
      name: "Gel",
      price: 0.8,
      tagName: "gel",
      imageUrl: "/images/of23.png",
      targetModal: "#myModal24",
      numbers: 0,
      inCart: false,
      labelPrice: "1.00",
      itemWeight: "(150 g)",
      isOffer: false,
    },
    babyoil: {
      name: "Baby Oil",
      price: 6.0,
      tagName: "babyoil",
      imageUrl: "/images/of36.png",
      targetModal: "#myModal1",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(250 g)",
      isOffer: false,
    },
    soap: {
      name: "Soap",
      price: 4.5,
      tagName: "soap",
      imageUrl: "/images/of37.png",
      targetModal: "#myModal2",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(250 g)",
      isOffer: false,
    },
    hairgel: {
      name: "Hair Gel",
      price: 3.5,
      tagName: "hairgel",
      imageUrl: "/images/of38.png",
      targetModal: "#myModall3",
      numbers: 0,
      inCart: false,
      labelPrice: "4.00",
      itemWeight: "(250 g)",
      isOffer: false,
    },
    lotion: {
      name: "Lotion",
      price: 0.8,
      tagName: "lotion",
      imageUrl: "/images/of39.png",
      targetModal: "#myModal4",
      numbers: 0,
      inCart: false,
      labelPrice: "1",
      itemWeight: "(100 g)",
      isOffer: false,
    },
    showergel: {
      name: "Shower Gel",
      price: 6,
      tagName: "showergel",
      imageUrl: "/images/of40.png",
      targetModal: "#myModal5",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(250 g)",
      isOffer: false,
    },
    haircolor: {
      name: "Hair Color",
      price: 4.5,
      tagName: "haircolor",
      imageUrl: "/images/of41.png",
      targetModal: "#myModal6",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(250 g)",
      isOffer: false,
    },
    wipes: {
      name: "Wipes",
      price: 3,
      tagName: "wipes",
      imageUrl: "/images/of42.png",
      targetModal: "#myModal7",
      numbers: 0,
      inCart: false,
      labelPrice: "4.00",
      itemWeight: "(300 kg)",
      isOffer: false,
    },
    essentialoils: {
      name: "Essential Oils",
      price: 1.0,
      tagName: "essentialoils",
      imageUrl: "/images/of43.png",
      targetModal: "#myModal8",
      numbers: 0,
      inCart: false,
      labelPrice: "0.80",
      itemWeight: "(200 g)",
      isOffer: false,
    },
    cream: {
      name: "Cream",
      price: 6,
      tagName: "cream",
      imageUrl: "/images/of44.png",
      targetModal: "#myModal9",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(150 g)",
      isOffer: false,
    },
    haircolor: {
      name: "Hair Color",
      price: 4.5,
      tagName: "haircolor",
      imageUrl: "/images/of45.png",
      targetModal: "#myModall10",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(250 g)",
      isOffer: false,
    },
    babycare: {
      name: "Baby Care",
      price: 3.5,
      tagName: "babycare",
      imageUrl: "/images/of46.png",
      targetModal: "#myModal11",
      numbers: 0,
      inCart: false,
      labelPrice: "4",
      itemWeight: "(1 kg)",
      isOffer: false,
    },
    lotion: {
      name: "Lotion",
      price: 0.8,
      tagName: "lotion",
      imageUrl: "/images/of47.png",
      targetModal: "#myModal12",
      numbers: 0,
      inCart: false,
      labelPrice: "1.00",
      itemWeight: "(100 g)",
      isOffer: false,
    },
    catfood: {
      name: "Cat Food",
      price: 6.0,
      tagName: "catfood",
      imageUrl: "/images/of48.png",
      targetModal: "#myModal1",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(500 g)",
      isOffer: false,
    },
    safetypins: {
      name: "Safety Pins",
      price: 4.5,
      tagName: "safetypins",
      imageUrl: "/images/of49.png",
      targetModal: "#myModal2",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(100 g)",
      isOffer: false,
    },
    agarbatti: {
      name: "Agarbatti",
      price: 3.5,
      tagName: "agarbatti",
      imageUrl: "/images/of50.png",
      targetModal: "#myModall3",
      numbers: 0,
      inCart: false,
      labelPrice: "4.00",
      itemWeight: "(200 g)",
      isOffer: false,
    },
    candleset: {
      name: "Candle Set",
      price: 0.8,
      tagName: "candleset",
      imageUrl: "/images/of51.png",
      targetModal: "#myModal4",
      numbers: 0,
      inCart: false,
      labelPrice: "1",
      itemWeight: "(1 pc)",
      isOffer: false,
    },
    dustbin: {
      name: "Dust Bin",
      price: 6,
      tagName: "dustbin",
      imageUrl: "/images/of52.png",
      targetModal: "#myModal5",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(1 pc)",
      isOffer: false,
    },
    hanger: {
      name: "Hanger",
      price: 4.5,
      tagName: "hanger",
      imageUrl: "/images/of53.png",
      targetModal: "#myModal6",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(1 pc)",
      isOffer: false,
    },
    petbowl: {
      name: "Pet Bowl",
      price: 3,
      tagName: "petbowl",
      imageUrl: "/images/of54.png",
      targetModal: "#myModal7",
      numbers: 0,
      inCart: false,
      labelPrice: "4.00",
      itemWeight: "(1 pc)",
      isOffer: false,
    },
    tailum: {
      name: "Tailum",
      price: 1.0,
      tagName: "tailum",
      imageUrl: "/images/of55.png",
      targetModal: "#myModal8",
      numbers: 0,
      inCart: false,
      labelPrice: "0.80",
      itemWeight: "(500 g)",
      isOffer: false,
    },
    container: {
      name: "Container",
      price: 6,
      tagName: "container",
      imageUrl: "/images/of56.png",
      targetModal: "#myModal9",
      numbers: 0,
      inCart: false,
      labelPrice: "7.00",
      itemWeight: "(1 pc)",
      isOffer: false,
    },
    scrubsponge: {
      name: "Scrub Sponge",
      price: 4.5,
      tagName: "scrubsponge",
      imageUrl: "/images/of57.png",
      targetModal: "#myModall10",
      numbers: 0,
      inCart: false,
      labelPrice: "5.00",
      itemWeight: "(100 g)",
      isOffer: false,
    },
    reindeer: {
      name: "Reindeer",
      price: 3.5,
      tagName: "reindeer",
      imageUrl: "/images/of58.png",
      targetModal: "#myModal11",
      numbers: 0,
      inCart: false,
      labelPrice: "4",
      itemWeight: "(1 pc)",
      isOffer: false,
    },
    cleaner: {
      name: "Cleaner",
      price: 0.8,
      tagName: "cleaner",
      imageUrl: "/images/of59.png",
      targetModal: "#myModal12",
      numbers: 0,
      inCart: false,
      labelPrice: "1.00",
      itemWeight: "(1 pc)",
      isOffer: false,
    },
  },
};
export default (state = initialState, action) => {
  let productSelected = "";
  switch (action.type) {
    case ADD_TO_CART:
      productSelected = { ...state.products[action.payload] };
      productSelected.numbers += 1;
      productSelected.inCart = true;
      return {
        ...state,
        cart: state.cart + 1,
        cartPrice: state.cartPrice + state.products[action.payload].price,
        products: {
          ...state.products,
          [action.payload]: productSelected,
        },
      };
    case GET_NUMBERS_BASKET:
      return {
        ...state,
      };
    case INCREASE_QUANTITY:
      productSelected = { ...state.products[action.payload] };
      productSelected.numbers += 1;
      return {
        ...state,
        cart: state.cart + 1,
        cartPrice:
          Math.round(
            (state.cartPrice + state.products[action.payload].price) * 100
          ) / 100,
        products: {
          ...state.products,
          [action.payload]: productSelected,
        },
      };
    case DECREASE_QUANTITY:
      productSelected = { ...state.products[action.payload] };
      let newCartPrice = 0;
      let newCartNumbers = 0;
      if (productSelected.numbers === 0) {
        productSelected.numbers = 0;
        newCartPrice = state.cartPrice;
        newCartNumbers = state.cart;
      } else {
        productSelected.numbers -= 1;
        newCartPrice =
          Math.ceil(
            (state.cartPrice - state.products[action.payload].price) * 100
          ) / 100;
        newCartNumbers = state.cart - 1;
      }
      return {
        ...state,
        cart: newCartNumbers,
        cartPrice: newCartPrice,
        products: {
          ...state.products,
          [action.payload]: productSelected,
        },
      };
    case CLEAR_PRODUCT:
      productSelected = { ...state.products[action.payload] };
      let numbersBackup = productSelected.numbers;
      productSelected.numbers = 0;
      productSelected.inCart = false;
      return {
        ...state,
        cartPrice: state.cartPrice - numbersBackup * productSelected.price,
        cart: state.cart - numbersBackup,
        products: {
          ...state.products,
          [action.payload]: productSelected,
        },
      };
    default:
      return state;
  }
};