export const offerItems = [
  {
    name: "Moong",
    price: 1,
    tagName: "moong",
    imageUrl: "/images/of.png",
    targetModal: "#myModal1",
    numbers: 0,
    inCart: false,
    labelPrice: "2.00",
    itemWeight: "(1 kg)",
    isOffer: true,
  },
  {
    name: "Sunflower Oil",
    price: 9,
    tagName: "sunflower",
    imageUrl: "/images/of1.png",
    targetModal: "#myModal2",
    numbers: 0,
    inCart: false,
    labelPrice: "10.00",
    itemWeight: "(5 kg)",
    isOffer: true,
  },
  {
    name: "Kabuli Chana",
    price: 3,
    tagName: "kabulichana",
    imageUrl: "/images/of2.png",
    targetModal: "#myModal3",
    numbers: 0,
    inCart: false,
    labelPrice: "3.00",
    itemWeight: "(1 kg)",
    isOffer: true,
  },
  {
    name: "Soya Chunks",
    price: 3.5,
    tagName: "moong",
    imageUrl: "/images/of3.png",
    targetModal: "#myModal4",
    numbers: 0,
    inCart: false,
    labelPrice: "4.00",
    itemWeight: "(1 kg)",
    isOffer: true,
  },
];

export const essentialGrocery = [
  {
    name: "Moisturiser",
    price: 6.0,
    tagName: "moisturiser",
    imageUrl: "/images/of16.png",
    targetModal: "#myModal17",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(500 g)",
    isOffer: false,
  },
  {
    name: "Lady Finger",
    price: 4.5,
    tagName: "ladyfinger",
    imageUrl: "/images/of17.png",
    targetModal: "#myModall8",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Ribbon",
    price: 3.5,
    tagName: "ribbon",
    imageUrl: "/images/of18.png",
    targetModal: "#myModall9",
    numbers: 0,
    inCart: false,
    labelPrice: "4.00",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
  {
    name: "Grapes",
    price: 0.8,
    tagName: "grapes",
    imageUrl: "/images/of19.png",
    targetModal: "#myModal20",
    numbers: 0,
    inCart: false,
    labelPrice: "1",
    itemWeight: "(1 pack)",
    isOffer: false,
  },
  {
    name: "Clips",
    price: 6,
    tagName: "clips",
    imageUrl: "/images/of20.png",
    targetModal: "#myModal21",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(1 pack)",
    isOffer: false,
  },
  {
    name: "Conditioner",
    price: 4.5,
    tagName: "conditioner",
    imageUrl: "/images/of21.png",
    targetModal: "#myModal22",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Cleaner",
    price: 3,
    tagName: "cleaner",
    imageUrl: "/images/of22.png",
    targetModal: "#myModal23",
    numbers: 0,
    inCart: false,
    labelPrice: "4.00",
    itemWeight: "(250 kg)",
    isOffer: false,
  },
  {
    name: "Gel",
    price: 0.8,
    tagName: "gel",
    imageUrl: "/images/of23.png",
    targetModal: "#myModal24",
    numbers: 0,
    inCart: false,
    labelPrice: "1.00",
    itemWeight: "(150 g)",
    isOffer: false,
  },
];

export const personalCareItems = [
  {
    name: "Baby Oil",
    price: 6.0,
    tagName: "babyoil",
    imageUrl: "/images/of36.png",
    targetModal: "#myModal1",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Soap",
    price: 4.5,
    tagName: "soap",
    imageUrl: "/images/of37.png",
    targetModal: "#myModal2",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Hair Gel",
    price: 3.5,
    tagName: "hairgel",
    imageUrl: "/images/of38.png",
    targetModal: "#myModall3",
    numbers: 0,
    inCart: false,
    labelPrice: "4.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Lotion",
    price: 0.8,
    tagName: "lotion",
    imageUrl: "/images/of39.png",
    targetModal: "#myModal4",
    numbers: 0,
    inCart: false,
    labelPrice: "1",
    itemWeight: "(100 g)",
    isOffer: false,
  },
  {
    name: "Shower Gel",
    price: 6,
    tagName: "showergel",
    imageUrl: "/images/of40.png",
    targetModal: "#myModal5",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Hair Color",
    price: 4.5,
    tagName: "haircolor",
    imageUrl: "/images/of41.png",
    targetModal: "#myModal6",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Wipes",
    price: 3,
    tagName: "wipes",
    imageUrl: "/images/of42.png",
    targetModal: "#myModal7",
    numbers: 0,
    inCart: false,
    labelPrice: "4.00",
    itemWeight: "(300 kg)",
    isOffer: false,
  },
  {
    name: "Essential Oils",
    price: 1.0,
    tagName: "essentialoils",
    imageUrl: "/images/of43.png",
    targetModal: "#myModal8",
    numbers: 0,
    inCart: false,
    labelPrice: "0.80",
    itemWeight: "(200 g)",
    isOffer: false,
  },
  {
    name: "Cream",
    price: 6,
    tagName: "cream",
    imageUrl: "/images/of44.png",
    targetModal: "#myModal9",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(150 g)",
    isOffer: false,
  },
  {
    name: "Hair Color",
    price: 4.5,
    tagName: "haircolor",
    imageUrl: "/images/of45.png",
    targetModal: "#myModall10",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(250 g)",
    isOffer: false,
  },
  {
    name: "Baby Care",
    price: 3.5,
    tagName: "babycare",
    imageUrl: "/images/of46.png",
    targetModal: "#myModal11",
    numbers: 0,
    inCart: false,
    labelPrice: "4",
    itemWeight: "(1 kg)",
    isOffer: false,
  },
  {
    name: "Lotion",
    price: 0.8,
    tagName: "lotion",
    imageUrl: "/images/of47.png",
    targetModal: "#myModal12",
    numbers: 0,
    inCart: false,
    labelPrice: "1.00",
    itemWeight: "(100 g)",
    isOffer: false,
  },
];

export const HouseholdItems = [
  {
    name: "Cat Food",
    price: 6.0,
    tagName: "catfood",
    imageUrl: "/images/of48.png",
    targetModal: "#myModal1",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(500 g)",
    isOffer: false,
  },
  {
    name: "Safety Pins",
    price: 4.5,
    tagName: "safetypins",
    imageUrl: "/images/of49.png",
    targetModal: "#myModal2",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(100 g)",
    isOffer: false,
  },
  {
    name: "Agarbatti",
    price: 3.5,
    tagName: "agarbatti",
    imageUrl: "/images/of50.png",
    targetModal: "#myModall3",
    numbers: 0,
    inCart: false,
    labelPrice: "4.00",
    itemWeight: "(200 g)",
    isOffer: false,
  },
  {
    name: "Candle Set",
    price: 0.8,
    tagName: "candleset",
    imageUrl: "/images/of51.png",
    targetModal: "#myModal4",
    numbers: 0,
    inCart: false,
    labelPrice: "1",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
  {
    name: "Dust Bin",
    price: 6,
    tagName: "dustbin",
    imageUrl: "/images/of52.png",
    targetModal: "#myModal5",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
  {
    name: "Hanger",
    price: 4.5,
    tagName: "hanger",
    imageUrl: "/images/of53.png",
    targetModal: "#myModal6",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
  {
    name: "Pet Bowl",
    price: 3,
    tagName: "petbowl",
    imageUrl: "/images/of54.png",
    targetModal: "#myModal7",
    numbers: 0,
    inCart: false,
    labelPrice: "4.00",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
  {
    name: "Tailum",
    price: 1.0,
    tagName: "tailum",
    imageUrl: "/images/of55.png",
    targetModal: "#myModal8",
    numbers: 0,
    inCart: false,
    labelPrice: "0.80",
    itemWeight: "(500 g)",
    isOffer: false,
  },
  {
    name: "Container",
    price: 6,
    tagName: "container",
    imageUrl: "/images/of56.png",
    targetModal: "#myModal9",
    numbers: 0,
    inCart: false,
    labelPrice: "7.00",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
  {
    name: "Scrub Sponge",
    price: 4.5,
    tagName: "scrubsponge",
    imageUrl: "/images/of57.png",
    targetModal: "#myModall10",
    numbers: 0,
    inCart: false,
    labelPrice: "5.00",
    itemWeight: "(100 g)",
    isOffer: false,
  },
  {
    name: "Reindeer",
    price: 3.5,
    tagName: "reindeer",
    imageUrl: "/images/of58.png",
    targetModal: "#myModal11",
    numbers: 0,
    inCart: false,
    labelPrice: "4",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
  {
    name: "Cleaner",
    price: 0.8,
    tagName: "cleaner",
    imageUrl: "/images/of59.png",
    targetModal: "#myModal12",
    numbers: 0,
    inCart: false,
    labelPrice: "1.00",
    itemWeight: "(1 pc)",
    isOffer: false,
  },
];
